name: Sync
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   name: Sync to Gitee
            uses: wearerequired/git-mirror-action@master
            env:
                SSH_PRIVATE_KEY: ${{ secrets.GITEE_GITHUB_RSA_PRIVATE_KEY }}
            with:
                source-repo: "git@github.com:oneflyingfish/oneflyingfish.github.io.git"
                destination-repo: "git@gitee.com:oneflyingfish/oneflyingfish.git"

        -   name: Build Gitee Pages
            uses: yanglbme/gitee-pages-action@master
            with:
                gitee-username: oneflyingfish
                gitee-password: ${{ secrets.GITEE_PASSWORD }}
                gitee-repo: oneflyingfish/oneflyingfish
                branch:  main
